name: Creating Artifacts
on: [push]
jobs:
  Linux-Artifact:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: joschi/setup-jdk@v2
        with:
          java-version: '17'
      - name: Build with Maven
        run: mvn package
      - name: Get job's artifacts
        uses: actions/upload-artifact@v2
        with:
          name: TBS-ubuntu
          path: target/TBS.jar

  Mac-Artifact:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: joschi/setup-jdk@v2
        with:
          java-version: '17'
      - name: Build with Maven
        run: mvn package
      - name: Get job's artifacts
        uses: actions/upload-artifact@v2
        with:
          name: TBS-mac
          path: target/TBS.jar

  Windows-Artifact:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: joschi/setup-jdk@v2
        with:
          java-version: '17'
      - name: Build with Maven
        run: mvn package
      - name: Get job's artifacts
        uses: actions/upload-artifact@v2
        with:
          name: TBS-windows
          path: target/TBS.jar
  Release:
    runs-on: ubuntu-latest
    needs: [Linux-Artifact, Mac-Artifact, Windows-Artifact]
    steps:
      - name: Download Linux artifact
        uses: actions/download-artifact@v2
        with:
          name: TBS-ubuntu
          path: ubuntu/
      - name: Rename Ubuntu
        run: mv ubuntu/TBS.jar ubuntu/TBS-linux.jar

      - name: Download Mac artifact
        uses: actions/download-artifact@v2
        with:
          name: TBS-mac
          path: mac/
      - name: Rename Mac
        run: mv mac/TBS.jar mac/TBS-mac.jar

      - name: Download Windows artifact
        uses: actions/download-artifact@v2
        with:
          name: TBS-windows
          path: windows/
      - name: Rename Windows
        run: mv windows/TBS.jar windows/TBS-windows.jar

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          draft: true
          files: |
            ubuntu/TBS-linux.jar
            mac/TBS-mac.jar
            windows/TBS-windows.jar

